# Generated by Django 5.2.15 on 2026-06-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0002_catalogueproduct_medication_catalogue_product_and_more"),
        ("inventory", "0002_stockmovement"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("horizon_days", models.PositiveIntegerField(default=30)),
                ("lookback_days", models.PositiveIntegerField(default=90)),
                (
                    "model_version",
                    models.CharField(default="baseline-1", max_length=32),
                ),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        max_length=16,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_runs",
                        to="tenancy.group",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_runs",
                        to="tenancy.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ForecastItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication_label", models.CharField(max_length=255)),
                ("predicted_usage_units", models.PositiveIntegerField(default=0)),
                (
                    "predicted_usage_packs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("current_stock_units", models.PositiveIntegerField(default=0)),
                (
                    "current_stock_packs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("safety_stock_units", models.PositiveIntegerField(default=0)),
                ("suggested_reorder_units", models.PositiveIntegerField(default=0)),
                (
                    "suggested_reorder_packs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=3)),
                ("explanation", models.TextField()),
                ("history_points_count", models.PositiveIntegerField(default=0)),
                ("window_days", models.PositiveIntegerField(default=90)),
                (
                    "catalogue_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_items",
                        to="catalogue.catalogueproduct",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_items",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="analytics.forecastrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-suggested_reorder_units", "medication_label", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="forecastrun",
            index=models.Index(
                fields=["pharmacy", "-created_at"],
                name="analytics_f_pharmac_b153d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastitem",
            index=models.Index(
                fields=["run", "-suggested_reorder_units"],
                name="analytics_f_run_id_42efb1_idx",
            ),
        ),
    ]
