# Generated by Django 5.2.15 on 2026-06-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("catalogue", "0002_catalogueproduct_medication_catalogue_product_and_more"),
        ("inventory", "0002_stockmovement"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication_label", models.CharField(max_length=255)),
                ("suggested_quantity_units", models.PositiveIntegerField(default=0)),
                (
                    "suggested_quantity_packs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("current_source_stock_units", models.PositiveIntegerField(default=0)),
                (
                    "destination_recent_usage_units",
                    models.PositiveIntegerField(default=0),
                ),
                ("dead_days", models.PositiveIntegerField(default=30)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=3)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("DISMISSED", "Dismissed"),
                            ("ACTIONED", "Actioned"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="transfer-baseline-1", max_length=32),
                ),
                (
                    "catalogue_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_suggestions",
                        to="catalogue.catalogueproduct",
                    ),
                ),
                (
                    "destination_pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_transfer_suggestions",
                        to="tenancy.pharmacy",
                    ),
                ),
                (
                    "destination_stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_transfer_suggestions",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_suggestions",
                        to="tenancy.group",
                    ),
                ),
                (
                    "source_pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_transfer_suggestions",
                        to="tenancy.pharmacy",
                    ),
                ),
                (
                    "source_stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_transfer_suggestions",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-created_at",
                    "-suggested_quantity_units",
                    "medication_label",
                ],
                "indexes": [
                    models.Index(
                        fields=["group", "status", "-created_at"],
                        name="analytics_t_group_i_5dd61f_idx",
                    ),
                    models.Index(
                        fields=["catalogue_product", "status"],
                        name="analytics_t_catalog_32fae4_idx",
                    ),
                ],
            },
        ),
    ]
