# Generated by Django 6.0.6 on 2026-06-13 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('GENERAL_REVIEW', 'General review'), ('DOSETTE_REVIEW', 'Dosette review'), ('MEDICATION_CONCERN', 'Medication concern'), ('STOCK_RELATED', 'Stock-related note'), ('FOLLOW_UP_REQUIRED', 'Follow-up required')], db_index=True, max_length=30)),
                ('note_text', models.TextField()),
                ('review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('follow_up_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('REQUIRED', 'Required'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], db_index=True, default='NOT_REQUIRED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_clinical_review_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_review_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='clinical_patient_time')],
            },
        ),
    ]
