# Generated by Django 6.0.6 on 2026-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_clinicalreviewnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='care_setting',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('CARE_HOME', 'Care home'), ('OTHER', 'Other')], db_index=True, default='COMMUNITY', max_length=20),
        ),
    ]
