# Generated by Django 5.2.15 on 2026-06-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("COUNT_CORRECTION", "Count correction"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("BLISTER_DEDUCTION", "Blister deduction"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["stock_item", "created_at"],
                        name="inventory_s_stock_i_c40196_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_delta", 0), _negated=True),
                        name="stock_movement_nonzero_delta",
                    )
                ],
            },
        ),
    ]
