# Generated by Django 5.2.15 on 2026-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="pack_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
