# Generated by Django 5.2.15 on 2026-06-13 15:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosettePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly (4-week)')], default='weekly', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('review_date', models.DateField(blank=True, help_text='Dosage review due date.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosette_plans', to='patients.patient')),
            ],
            options={
                'ordering': ['-is_active', 'patient__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DosetteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_quantity', models.PositiveIntegerField(default=1)),
                ('schedule', models.JSONField(default=dict)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.medicine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dosette.dosetteplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DosetteCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('due_date', models.DateField(db_index=True, help_text='When the pack is needed.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_prep', 'In preparation'), ('assembled', 'Assembled'), ('checked', 'Final-checked'), ('sealed', 'Sealed')], default='scheduled', max_length=12)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('assembled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_cycles', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_cycles', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='dosette.dosetteplan')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='dosette_dos_status_f1aeef_idx')],
            },
        ),
    ]
