# Generated by Django 5.2.15 on 2026-06-13 15:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('account_ref', models.CharField(blank=True, max_length=40)),
                ('lead_time_days', models.PositiveIntegerField(default=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('strength', models.CharField(blank=True, max_length=40)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('inhaler', 'Inhaler'), ('sachet', 'Sachet'), ('other', 'Other')], default='tablet', max_length=20)),
                ('pack_size', models.PositiveIntegerField(default=28)),
                ('unit', models.CharField(default='tablet', max_length=20)),
                ('reorder_level', models.PositiveIntegerField(default=200)),
                ('reorder_quantity', models.PositiveIntegerField(default=500)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='stock.manufacturer')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='stock.supplier')),
            ],
            options={
                'ordering': ['name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=40)),
                ('expiry_date', models.DateField(db_index=True)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.supplier')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('receipt', 'Goods received'), ('dispense', 'Dispensed / picked'), ('adjust', 'Adjustment'), ('waste', 'Wastage'), ('return', 'Return to stock')], max_length=12)),
                ('quantity', models.IntegerField(help_text='Signed: negative removes stock.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='stock.medicine')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['medicine', 'date'], name='stock_medic_medicin_0370fd_idx')],
                'unique_together': {('medicine', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='stock_stock_medicin_873e1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('name', 'strength', 'form')},
        ),
    ]
