# Generated by Django 5.2.15 on 2026-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Critical'), ('success', 'Success')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('low_stock', 'Low stock'), ('expiry', 'Approaching expiry'), ('shortage', 'Predicted shortage'), ('review', 'Overdue review'), ('announcement', 'System announcement')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_read'], name='notificatio_categor_2b809e_idx')],
            },
        ),
    ]
