# Generated by Django 5.2.15 on 2026-06-15 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("address", models.TextField(blank=True)),
                ("postcode", models.CharField(blank=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacies",
                        to="tenancy.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("SUPERINTENDENT", "Superintendent"),
                            ("STOCK_EMPLOYEE", "Stock employee"),
                            ("PHARMACIST", "Pharmacist"),
                            ("DISPENSER", "Dispenser"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stock_memberships",
                        to="tenancy.pharmacy",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.pharmacy",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pharmacy",
            constraint=models.UniqueConstraint(
                fields=("group", "code"), name="unique_pharmacy_code_per_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("group__isnull", True),
                        ("pharmacy__isnull", True),
                        ("role", "ADMIN"),
                    ),
                    models.Q(
                        ("group__isnull", False),
                        ("pharmacy__isnull", True),
                        ("role", "SUPERINTENDENT"),
                    ),
                    models.Q(
                        ("group__isnull", False),
                        ("pharmacy__isnull", True),
                        ("role", "STOCK_EMPLOYEE"),
                    ),
                    models.Q(
                        ("group__isnull", True),
                        ("pharmacy__isnull", False),
                        ("role", "PHARMACIST"),
                    ),
                    models.Q(
                        ("group__isnull", True),
                        ("pharmacy__isnull", False),
                        ("role", "DISPENSER"),
                    ),
                    _connector="OR",
                ),
                name="membership_scope_matches_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="unique_active_membership_per_user",
            ),
        ),
    ]
