# Generated by Django 6.0.6 on 2026-06-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_stockbatch'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosetteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_dose', models.CharField(blank=True, max_length=50)),
                ('afternoon_dose', models.CharField(blank=True, max_length=50)),
                ('evening_dose', models.CharField(blank=True, max_length=50)),
                ('bedtime_dose', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosette_records', to='inventory.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosette_records', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'medication'],
            },
        ),
    ]
