# Generated by Django 6.0.6 on 2026-06-13 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('patients', '0003_patient_care_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=201)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('delivery_window', models.CharField(choices=[('ANYTIME', 'Any time'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='ANYTIME', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('assigned_username', models.CharField(blank=True, max_length=150)),
                ('instructions', models.TextField(blank=True, max_length=1000)),
                ('outcome_notes', models.TextField(blank=True, max_length=1000)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_deliveries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_local_deliveries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_deliveries', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_date', 'status', '-created_at'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='ops_delivery_date_status'), models.Index(fields=['assigned_user', 'status'], name='ops_delivery_user_status')],
            },
        ),
    ]
