# Generated by Django 6.0.6 on 2026-06-13 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_localdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeTemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('action_taken', models.TextField(blank=True, max_length=2000)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('recorded_by_username', models.CharField(blank=True, max_length=150)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_temperature_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
