# Generated by Django 6.0.6 on 2026-06-13 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_fridgetemperaturelog'),
        ('patients', '0003_patient_care_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('appointment_type', models.CharField(choices=[('GENERAL', 'General appointment'), ('PATIENT_REVIEW', 'Patient review'), ('DOSETTE_REVIEW', 'Dosette review'), ('SUPPLIER', 'Supplier meeting'), ('STAFF', 'Staff meeting'), ('OTHER', 'Other')], db_index=True, default='GENERAL', max_length=30)),
                ('patient_name', models.CharField(blank=True, max_length=201)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('assigned_username', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('outcome_notes', models.TextField(blank=True, max_length=2000)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operational_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_start', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_start'], name='ops_appt_status_start'), models.Index(fields=['assigned_user', 'scheduled_start'], name='ops_appt_user_start')],
            },
        ),
    ]
