# Generated by Django 6.0.6 on 2026-06-13 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operationalappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('OPERATIONS', 'Operations'), ('POLICY', 'Policy'), ('TRAINING', 'Training'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], db_index=True, default='OPERATIONS', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_resource_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'title'],
            },
        ),
    ]
