# Generated by Django 5.2.15 on 2026-06-15 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("actor_role", models.CharField(blank=True, max_length=32)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login failed"),
                            ("USER_CREATED", "User created"),
                            ("USER_DEACTIVATED", "User deactivated"),
                            ("PASSWORD_CHANGED", "Password changed"),
                            ("PASSWORD_RESET", "Password reset"),
                            ("ROLE_ASSIGNED", "Role assigned"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenancy.group",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenancy.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_0c0ad1_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="audit_audit_actor_i_40b234_idx"
                    ),
                    models.Index(
                        fields=["group", "created_at"],
                        name="audit_audit_group_i_3b4535_idx",
                    ),
                    models.Index(
                        fields=["pharmacy", "created_at"],
                        name="audit_audit_pharmac_5fdb36_idx",
                    ),
                ],
            },
        ),
    ]
