# Generated by Django 5.2.15 on 2026-06-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOGIN_FAILED", "Login failed"),
                    ("USER_CREATED", "User created"),
                    ("USER_DEACTIVATED", "User deactivated"),
                    ("USER_DELETED", "User deleted"),
                    ("PASSWORD_CHANGED", "Password changed"),
                    ("PASSWORD_RESET", "Password reset"),
                    ("ROLE_ASSIGNED", "Role assigned"),
                ],
                max_length=64,
            ),
        ),
    ]
