# Generated by Django 5.2.15 on 2026-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOGIN_FAILED", "Login failed"),
                    ("USER_CREATED", "User created"),
                    ("USER_DEACTIVATED", "User deactivated"),
                    ("USER_DELETED", "User deleted"),
                    ("PASSWORD_CHANGED", "Password changed"),
                    ("PASSWORD_RESET", "Password reset"),
                    ("ROLE_ASSIGNED", "Role assigned"),
                    ("GROUP_CREATED", "Group created"),
                    ("GROUP_UPDATED", "Group updated"),
                    ("PHARMACY_CREATED", "Pharmacy created"),
                    ("PHARMACY_UPDATED", "Pharmacy updated"),
                    ("MEDICATION_CREATED", "Medication created"),
                    ("MEDICATION_UPDATED", "Medication updated"),
                    ("PATIENT_CREATED", "Patient created"),
                    ("PATIENT_UPDATED", "Patient updated"),
                    ("PATIENT_DEACTIVATED", "Patient deactivated"),
                    ("PATIENT_NOTE_ADDED", "Patient note added"),
                    ("STOCK_RECEIVED", "Stock received"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_COUNT_RECONCILED", "Stock count reconciled"),
                    ("STOCK_TRANSFERRED", "Stock transferred"),
                ],
                max_length=64,
            ),
        ),
    ]
