# Generated by Django 5.2.15 on 2026-06-19 22:14

import django.db.models.deletion
from django.db import migrations, models

import apps.patients.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("patients", "0005_patientnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dose_instructions",
                    apps.patients.fields.EncryptedTextField(blank=True),
                ),
                ("quantity_morning", models.PositiveSmallIntegerField(default=0)),
                ("quantity_lunchtime", models.PositiveSmallIntegerField(default=0)),
                ("quantity_evening", models.PositiveSmallIntegerField(default=0)),
                ("quantity_bedtime", models.PositiveSmallIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_medication_lines",
                        to="catalogue.medication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_lines",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["medication__name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("patient", "medication"),
                        name="unique_active_medication_per_patient",
                    )
                ],
            },
        ),
    ]
