# Generated by Django 5.2.15 on 2026-06-19 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blister", "0001_initial"),
        ("patients", "0005_patientnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosetteCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=64)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("FORTNIGHTLY", "Fortnightly"),
                            ("FOUR_WEEKLY", "Four-weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREPARED", "Prepared"),
                            ("CHECKED", "Checked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dosette_cycles",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "reference"),
                        name="unique_cycle_reference_per_patient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="dosette_cycle_end_after_start",
                    ),
                ],
            },
        ),
    ]
