# Generated by Django 5.2.15 on 2026-06-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blister", "0002_dosettecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="dosettecycle",
            name="deducted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dosettecycle",
            name="stock_deducted",
            field=models.BooleanField(default=False),
        ),
    ]
