# Generated by Django 5.2.15 on 2026-06-28 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blister", "0004_dosettecycle_checked_at_dosettecycle_checked_by_and_more"),
        ("patients", "0006_patient_email_patient_gender_patient_title_patientgp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dosettecycle",
            name="week_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DosettePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("COLLECTED", "Collected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("collected_on", models.DateField(blank=True, null=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_dosette_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dosette_periods",
                        to="patients.patient",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_dosette_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="dosettecycle",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cycles",
                to="blister.dosetteperiod",
            ),
        ),
        migrations.AddConstraint(
            model_name="dosettecycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period__isnull", False)),
                fields=("period", "week_number"),
                name="unique_dosette_cycle_week_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="dosettecycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("week_number__isnull", True),
                    models.Q(("week_number__gte", 1), ("week_number__lte", 4)),
                    _connector="OR",
                ),
                name="dosette_cycle_week_number_1_to_4",
            ),
        ),
        migrations.AddConstraint(
            model_name="dosetteperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="dosette_period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="dosetteperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SUBMITTED")),
                fields=("patient",),
                name="unique_submitted_dosette_period_per_patient",
            ),
        ),
    ]
