# Generated by Django 6.0.6 on 2026-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Cream', 'Cream'), ('Inhaler', 'Inhaler'), ('Injection', 'Injection'), ('Other', 'Other')], max_length=20),
        ),
    ]
