# Generated by Django 5.2.15 on 2026-06-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("patient_reference", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField(blank=True)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="tenancy.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pharmacy", "patient_reference"),
                        name="unique_patient_reference_per_pharmacy",
                    )
                ],
            },
        ),
    ]
