# Generated by Django 5.2.15 on 2026-06-22 17:51

import django.db.models.deletion
from django.db import migrations, models

import apps.patients.fields


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_patientnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=apps.patients.fields.EncryptedTextField(
                blank=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=apps.patients.fields.EncryptedTextField(
                blank=True, max_length=40, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="title",
            field=apps.patients.fields.EncryptedTextField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="PatientGp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "practice_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "practice_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "practice_postcode",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "practice_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "practice_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gp",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
