# Generated by Django 6.0.6 on 2026-06-13 08:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def create_opening_balance_movements(apps, schema_editor):
    StockBatch = apps.get_model("inventory", "StockBatch")
    StockMovement = apps.get_model("inventory", "StockMovement")

    movements = []
    for batch in StockBatch.objects.select_related("medication").filter(
        quantity__gt=0
    ):
        medication = batch.medication
        movements.append(
            StockMovement(
                stock_batch=batch,
                stock_batch_identifier=str(batch.pk),
                medication_identifier=str(batch.medication_id),
                medication_name=(
                    f"{medication.name} {medication.strength} {medication.form}"
                ),
                batch_number=batch.batch_number,
                movement_type="RECEIVED",
                quantity_change=batch.quantity,
                quantity_before=0,
                quantity_after=batch.quantity,
                reason="Opening balance recorded during stock ledger migration.",
            )
        )

    StockMovement.objects.bulk_create(movements)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_batch_identifier', models.CharField(db_index=True, max_length=100)),
                ('medication_identifier', models.CharField(blank=True, max_length=100)),
                ('medication_name', models.CharField(max_length=250)),
                ('batch_number', models.CharField(max_length=100)),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('ADJUSTMENT', 'Adjustment'), ('PICKING_ALLOCATION', 'Picking allocation'), ('CORRECTION', 'Correction'), ('WASTE_QUARANTINE', 'Waste / quarantine')], db_index=True, max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['stock_batch_identifier', '-timestamp'], name='stock_move_batch_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='stock_movement_non_zero_change'), models.CheckConstraint(condition=models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '+', models.F('quantity_change')))), name='stock_movement_balances')],
            },
        ),
        migrations.RunPython(
            create_opening_balance_movements,
            migrations.RunPython.noop,
        ),
    ]
