# Generated by Django 6.0.6 on 2026-06-13 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medication',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medication',
            name='target_weeks_of_cover',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
