# Generated by Django 6.0.6 on 2026-06-13 09:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medication_minimum_stock_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('account_reference', models.CharField(blank=True, max_length=100)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(365)])),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DraftPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_purchase_orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_medications', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='DraftPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recommended_quantity', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
                ('target_stock', models.PositiveIntegerField()),
                ('rationale', models.CharField(max_length=300)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_purchase_order_items', to='inventory.medication')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.draftpurchaseorder')),
            ],
            options={
                'ordering': ['medication_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('purchase_order', 'medication'), name='unique_draft_po_medication')],
            },
        ),
        migrations.AddIndex(
            model_name='draftpurchaseorder',
            index=models.Index(fields=['supplier', 'status', '-created_at'], name='draft_po_supplier_status'),
        ),
    ]
