# Generated by Django 6.0.6 on 2026-06-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosette', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('prescription', 'Prescription'), ('dosette', 'Dosette / MDS'), ('stock_issue', 'Stock issue')], default='dosette', max_length=16)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('picking_required', 'Picking required'), ('picking_in_progress', 'Picking in progress'), ('picked', 'Picked'), ('accuracy_check', 'Accuracy check'), ('ready', 'Ready'), ('issue_found', 'Issue found'), ('collected', 'Collected / Delivered')], default='new', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('issue_notes', models.TextField(blank=True)),
                ('ai_meta', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('dosette_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_jobs', to='dosette.dosettecycle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_jobs', to='patients.patient')),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('changed_by_label', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_changes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowjob',
            index=models.Index(fields=['status', 'due_date'], name='workflow_wo_status_a4fc80_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowjob',
            index=models.Index(fields=['job_type', 'status'], name='workflow_wo_job_typ_ed25d8_idx'),
        ),
    ]
