# Generated by Django 5.2.15 on 2026-07-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="encrypted",
            field=models.BooleanField(default=False),
        ),
    ]
