# Generated by Django 5.2.15 on 2026-06-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("LIQUID", "Liquid"),
                            ("CREAM", "Cream"),
                            ("INHALER", "Inhaler"),
                            ("INJECTION", "Injection"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("strength", models.CharField(max_length=64)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medications",
                        to="tenancy.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "strength"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "name", "form", "strength"),
                        name="unique_medication_per_group",
                    )
                ],
            },
        ),
    ]
