# Generated by Django 5.2.15 on 2026-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_catalogueproduct_medication_catalogue_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogueproduct",
            name="dmd_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VMP", "Virtual medicinal product"),
                    ("AMP", "Actual medicinal product"),
                    ("VMPP", "Virtual medicinal product pack"),
                    ("AMPP", "Actual medicinal product pack"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="catalogueproduct",
            name="is_discontinued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogueproduct",
            name="parent_dmd_code",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="catalogueproduct",
            name="release_file",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="catalogueproduct",
            name="release_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="catalogueproduct",
            name="dose_form",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="catalogueproduct",
            name="source",
            field=models.CharField(
                choices=[
                    ("DMD", "dm+d"),
                    ("TRUD_DMD", "TRUD dm+d"),
                    ("SEED", "Seed"),
                    ("MANUAL", "Manual"),
                ],
                default="SEED",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogueproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dmd_code", ""), _negated=True),
                fields=("dmd_code",),
                name="unique_catalogue_product_dmd_code",
            ),
        ),
    ]
