# Generated by Django 5.2.15 on 2026-06-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.patients.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blister", "0003_dosettecycle_deducted_at_dosettecycle_stock_deducted"),
        ("patients", "0005_patientnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_REVIEW", "In review"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("ATTENTION", "Attention"),
                            ("URGENT", "Urgent"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", apps.patients.fields.EncryptedTextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dosette_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="blister.dosettecycle",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("due_date"), nulls_last=True),
                    "-created_at",
                    "-id",
                ],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="reviews_rev_patient_7a4188_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="reviews_rev_status_03a134_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="reviews_rev_assigne_7c1df0_idx",
                    ),
                ],
            },
        ),
    ]
