# Generated by Django 6.0.6 on 2026-06-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("text", models.CharField(db_index=True, max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dose", "Dose"),
                            ("timing", "Timing"),
                            ("route", "Route"),
                            ("qualifier", "Qualifier"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "category", "sort_order"],
                        name="directions__is_acti_9d74f1_idx",
                    )
                ],
            },
        ),
    ]
