# Generated by Django 6.0.6 on 2026-06-13 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosette', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosetterecord',
            name='cycle_length_weeks',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='dosetterecord',
            name='cycle_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dosetterecord',
            name='review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='DosetteMedicationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosette_record_identifier', models.PositiveBigIntegerField(db_index=True)),
                ('patient_identifier', models.PositiveBigIntegerField(db_index=True)),
                ('patient_name', models.CharField(max_length=250)),
                ('medication_identifier', models.PositiveBigIntegerField(db_index=True)),
                ('medication_name', models.CharField(max_length=250)),
                ('change_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('DELETED', 'Deleted')], db_index=True, max_length=20)),
                ('changed_fields', models.JSONField(default=list)),
                ('morning_dose', models.CharField(blank=True, max_length=50)),
                ('afternoon_dose', models.CharField(blank=True, max_length=50)),
                ('evening_dose', models.CharField(blank=True, max_length=50)),
                ('bedtime_dose', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField()),
                ('cycle_start_date', models.DateField(blank=True, null=True)),
                ('cycle_length_weeks', models.PositiveSmallIntegerField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosette_medication_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['patient_identifier', '-timestamp'], name='dosette_change_patient_time'), models.Index(fields=['dosette_record_identifier', '-timestamp'], name='dosette_change_record_time')],
            },
        ),
    ]
